stations:
  - id: 1
    name: "Estación 1"
    pose:
      position:
        x: 2.0
        y: 0.0
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    allowed_objects: ["botella", "vaso"]

  - id: 2
    name: "Estación 2"
    pose:
      position:
        x: 0.0
        y: 2.0
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.707
        w: 0.707
    allowed_objects: ["pelota", "juguete"]

  - id: 3
    name: "Estación 3"
    pose:
      position:
        x: -2.0
        y: 0.0
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 1.0
        w: 0.0
    allowed_objects: ["libro", "caja"] 